site_name: Connectivity kir for Kuka robots
site_url: https://github.com/ramp-eu/JS2SF
repo_url: https://github.com/ramp-eu/JS2SF
site_description: Rose AP Documentation and software for the connectivity kit for Kuka robotos. 
docs_dir: docs
site_dir: html
edit_uri: edit/master/doc/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - Home: 'index.md'
  - 'Getting Started' : 'getting-started.md'
  - 'Installation & Administration Manual': 
    - 'Installation Guide': 'installationguide.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'User Guide': 'usermanual.md'
    - 'API' : 'api.md'
