{
 "title": "Pallet_Dashboard_Operator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Pallet",
    "label": "Pallet",
    "query": "SELECT DISTINCT substr(entity_id,20,4) AS \"RC_ID\" FROM etpallet ORDER BY \"RC_ID\" ASC"
   }
  ]
 },
 "panels": [
  { "title": "Pallet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Pallet" },
  {
   "title": "PalletID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT palletid\nFROM etpallet \nWHERE (substr(entity_id,20,4) IN ($Pallet))\nORDER BY time_index DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "stuklijst",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  refpiecelist\nFROM etpallet \nWHERE (substr(entity_id,20,4) IN ($Pallet))\nORDER BY time_index DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "refcurrentlocation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT  (substr(refcurrentlocation,13,20)) as currentlocation\nFROM etpallet \nWHERE (substr(entity_id,20,4) IN ($Pallet))\nORDER BY time_index DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "refgointo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT  (substr(refgoingto,13,20)) as goingto\nFROM etpallet \nWHERE (substr(entity_id,20,4) IN ($Pallet))\nORDER BY time_index DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "manufactureabilityonflexedge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT  manufacturabilityonflexedge\nFROM etpallet \nWHERE (substr(entity_id,20,4) IN ($Pallet))\nORDER BY time_index DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Pallet",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 8 },
   "options": {
    "content": "<img src=\"https://www.optidrive.be/themes/custom/optidrive/logo.svg\" style=\"width:360px;height:200px;\"/>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}