{
 "title": "Roboticcell_Dashboard_final",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "RoboticCell",
    "label": "RoboticCell",
    "query": "SELECT DISTINCT substr(entity_id,25,8) AS \"RC_ID\" FROM etroboticcell ORDER BY \"RC_ID\" ASC"
   }
  ]
 },
 "panels": [
  { "title": "RoboticCell", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "RoboticCell" },
  {
   "title": "RoboticCell",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT  (substr(entity_id,13,20)) as entity FROM \"doc\".\"etroboticcell\"  WHERE (substr(entity_id,25,8) IN ($RoboticCell)) LIMIT 1;"
    }
   ]
  },
  {
   "title": "refincomingpallet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  (substr(refincomingpallet,13,20)) as incoming\nFROM etroboticcell \nWHERE (substr(entity_id,25,8) IN ($RoboticCell))\nORDER BY time_index DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "refoutgoingpallet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  (substr(refoutgoingpallet,13,20)) as outgoing\nFROM etroboticcell \nWHERE (substr(entity_id,25,8) IN ($RoboticCell))\nORDER BY time_index DESC\nLIMIT 1;\n\n"
    }
   ]
  },
  {
   "title": "Robot",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": {
    "content": "<img src=\"https://www.optidrive.be/themes/custom/optidrive/logo.svg\" style=\"width:360px;height:200px;\"/>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Number of pieces done",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT currentpiecenumber\nFROM etrobot\nWHERE (substr(entity_id,19,6)) IN (substr($RoboticCell,0,6))\nORDER BY time_index DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Total number of pieces",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT totalnumberofpieces\nFROM etrobot\nWHERE (substr(entity_id,19,6)) IN (substr($RoboticCell,0,6))\nORDER BY time_index DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Pallet Log",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \"refincomingpallet\",\"refoutgoingpallet\",\"time_index\" FROM \"doc\".\"etroboticcell\" WHERE (substr(entity_id,25,8) IN ($RoboticCell)) ORDER BY time_index DESC LIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT status\nFROM etrobot\nWHERE (substr(entity_id,19,6)) IN (substr($RoboticCell,0,6))\nORDER BY time_index DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Current Errornumber",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  errornumber\nFROM etroboticcell \nWHERE (substr(entity_id,25,8) IN ($RoboticCell))\nORDER BY time_index DESC\nLIMIT 1;\n\n"
    }
   ]
  },
  {
   "title": "Robot info",
   "type": "table",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"entity_id\",\"entity_type\",\"jobname\",\"programname\",\"robotmodel\",\"toolid\",\"toolmodel\"\nFROM etrobot \nWHERE (substr(entity_id,19,6)) IN (substr($RoboticCell,0,6))\nORDER BY time_index DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Error Log",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \"errormessage\",\"errornumber\",\"time_index\" FROM \"doc\".\"etroboticcell\" WHERE (substr(entity_id,25,8) IN ($RoboticCell)) ORDER BY time_index DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Vaccuumpump",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \"entity_id\", \"on\",\"vacuumlevel\",\"time_index\" FROM \"doc\".\"etvacuumpump\" WHERE (substr(entity_id,24,6)) IN (substr($RoboticCell,0,6)) ORDER BY time_index DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Vacuumlevel",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT vacuumlevel\nFROM etvacuumpump \nWHERE (substr(entity_id,24,6)) IN (substr($RoboticCell,0,6))\nORDER BY time_index DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Robot Axis DuoCutRobot",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"axis1\", \"axis2\", \"axis3\", \"axis4\", \"axis5\", \"axis6\"\nFROM etrobot\nWHERE (substr(entity_id,19,6)) IN (substr($RoboticCell,0,6))\nORDER BY time_index DESC\nLIMIT 1;\n\n"
    }
   ]
  }
 ]
}