name: .NET

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

# nuget packages
    - name: Install dependencies
      run: dotnet restore src/KukaConnectROSE-AP.sln

    - name: Mkdir bin\Debug
      run: mkdir src\KukaConnectROSE-AP\bin\Debug
      
    - name: Copy RobotConnection dll
      run: copy bin\KukaBe.RobotConnection.dll src\KukaConnectROSE-AP\bin\Debug
      
    - name: Copy Network dll
      run: copy bin\KukaBe.Network.dll src\KukaConnectROSE-AP\bin\Debug\
      
    - name: Build
      run: dotnet build src/KukaConnectROSE-AP.sln

