name: .NET

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: dependencies
      run: dotnet publish src/KukaConnectROSE-AP.sln
      
    - name: Install dependencies
      run: dotnet add package Newtonsoft.Json --version 12.0.1
      
    - name: Build
      run: dotnet build src/KukaConnectROSE-AP.sln

